# Generated by Django 6.0.2 on 2026-09-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavstevaWebu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(unique=True)),
                ('pocet', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'návštěva webu',
                'verbose_name_plural': 'návštěvy webu',
                'ordering': ['-datum'],
            },
        ),
    ]
